services:
  moodleusp:
    build: .
    container_name: moodleusp
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - moodleusp-network
    volumes:
      - ./:/var/www/html
      - ./docker/moodleusp/install.sh:/install.sh
      - moodledata:/var/www/moodledata
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=1024M
    container_name: moodleusp_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: moodleusp
      MYSQL_USER: moodleusp
      MYSQL_PASSWORD: moodleusp
      MYSQL_ROOT_PASSWORD: moodleusp

    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - moodleusp-network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: moodleusp_phpmyadmin
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: moodleusp
    networks:
      - moodleusp-network

  senhaunica-faker:
    image: uspdev/senhaunica-faker
    container_name: moodleusp_senhaunica-faker
    ports:
      - "3141:3141"
    environment:
          - APP_URL=http://auth.local:3141
    networks:
      moodleusp-network:
        aliases:
          - auth.local

  mailpit:
    image: axllent/mailpit:latest
    container_name: moodleusp_mailpit
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Interface Web
    networks:
      - moodleusp-network

networks:
  moodleusp-network:

volumes:
  mariadb_data:
  moodledata: