services:
  moodleusp:
    image: moodleusp:latest
    container_name: moodleusp
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - moodleusp-network
    volumes:
      - ./:/var/www/html
      - ./docker/moodleusp/install.sh:/install.sh
      - moodledata:/var/www/moodledata
    environment:
      HOME: /tmp
    user: "${UID:-1000}:${GID:-1000}"

  mariadb:
    image: mariadb:11
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=1024M
    container_name: moodleusp_mariadb
    restart: always
    environment:
      MYSQL_DATABASE: moodleusp
      MYSQL_USER: moodleusp
      MYSQL_PASSWORD: moodleusp
      MYSQL_ROOT_PASSWORD: moodleusp

    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - moodleusp-network

networks:
  moodleusp-network:

volumes:
  mariadb_data:
  moodledata: